### ISSUE TITLE
Error Message #1

### ISSUE THREAD

**Issue by Finrodi** [laytya/CustomNameplates#1]
http://i.imgur.com/djt37BD.png

I have no idea how all this stuff works as well, dont remember exactly when I got this message but maybe this still helps.

**Comment by laytya** [comment]
never seen errors like this. Will track it. Do you have last version?

**Comment by Bifidus** [comment]
Latest version, i got this error : http://i.imgur.com/DI9a4lI.png
Also, i had to rename the folder to make the game see it (it miss a "e" in Nam"e"Plates).

**Comment by laytya** [comment]
ah. ok thx for name will fix it

about error  - need more testing

**Comment by laytya** [comment]
fixed, try

**Comment by Bifidus** [comment]
latest version : http://i.imgur.com/j11ejlf.png

**Comment by laytya** [comment]
logout and del CustomNameplates.lua in WTF folder.

**Comment by Bifidus** [comment]
Working mostly fine, now, no error.
But the ability to "click turn" on a nameplate have disapeared. You can't click through a nameplate with right click anymore (and that's the main reason i use an nameplate addon ^^)
Also, you can see only half of the debuff, and no duration : http://i.imgur.com/uYFOrZe.png

**Comment by laytya** [comment]
what is mean "click turn"?

you can set option "click through" in settings.lua

**Comment by Bifidus** [comment]
click turn : you right click and turn your caracter, instead of using direction keys.
But with the defaul UI, or CustomNameplate (not the previous one of Roadblock), if you happen to right click on a nameplate, nothing happen : you can't turn. It's a major annoyance, especially for melees, who are surrounded by nameplates.
That's the main reason, for me, to use a nameplate addon : so i can right click turn.
I put ["clickThrough"]=true (instead of false) in settings.lua, and restarted the game, but it did not change anything.

**Comment by laytya** [comment]
always logout and del CustomNameplates.lua in WTF folder if u change settings

**Comment by Bifidus** [comment]
Doh!
I did, and now it's working fine, thank you.
Can you put the default behavior of click through on "true", so we can avoid all the hassle to manually find and delete these WTF files (how that thing is working, by the way ? why do we have to do that ?) ?
Why put it on "false", anyhow ? Is there a reason for NOT wanting to click through ?

**Comment by laytya** [comment]
I dont use tab for selecting targets - it so.... to many mistakes. So I need click to nameplates. Now Im playing tank role =). I ll make options later - all mess will go away
